// backupBlogData.ts
// Fallback blog stories for frontend display if backend is unavailable

export const backupBlogData = [
  {
    id: 1,
    title: "How I Herded Hearts Instead of Sheep",
    author: "Karen",
    date: "2025-09-15",
    category: "MoonshinesCorner",
    NewsSection: "Moonshine's Corner",
    image: "/images/moonshine.jpg",
    article: "Woof! My name is Moonshine. Mom is in the other room, and she's working as always. Since my mother is busy, I wanted to share my tale of how I put smiles on my mom's patients' faces and learned about senior care. It started about a year and a half ago when Mom took me to some training to be a service dog. However, I got scared and it didn't work out! That's when Mom had a brilliant idea. She started taking me into the nursing home where she works. Not to brag or anything, but I was a hit. Most people there were very nice. I got lots of love from the residents. They all wanted to hold me and give me treats. Mom always brings special soft training treats that are easy for seniors with arthritis to hold and gentle on my tummy. In turn, I made them smile. Sometimes it was sad because some of the residents acted a little different and yelled a lot, and that scared me. Mom said it was because they had dementia or Alzheimer's and couldn't remember things. I still don't know what those big names mean, but Mom reassured me and said we would get some more treats if I continued to go and make the residents smile.",
    link: "./blogentries/moonshinesblogentry",
  },
  {
    id: 2,
    title: "Medicare Home Health Services: What Seniors Need to Know",
    author: "Karen Underwood RN BSN",
    date: "2025-09-15",
    category: "SeniorPolicyBeat",
    NewsSection: "Senior Policy Beat",
    image: "/images/medicare.jpg",
    article: "Medicare home health services can provide essential support for seniors, including skilled nursing care, physical therapy, and home health aide services. This article explains the origins of Home Health and how it has evolved to meet the needs of seniors today and changed to limit the ability of nurses to provide personal care to seniors.",
    link: "./blogentries/seniorpolicybeatblogentry",
  },
  {
    id: 3,
    title: "The Heart of Hospice Nursing: Compassion, Comfort, and Connection",
    author: "Rehab Solutions Team",
    date: "2025-09-15",
    category: "rehabsolutions",
    NewsSection: "Voices In Care",
    image: "/images/hospice.jpg",
    article: "A reflection upon the importance of Hospice nurses from our very own Hospice nurse.",
    link: "./blogentries/voicesincareblogentries",
  },
  {
    id: 4,
    title: "What to do before you die",
    author: "Karen Underwood RN BSN",
    date: "2025-09-15",
    category: "Senior Living Desk",
    NewsSection: "What to do before you die",
    image: "/images/death.jpg",
    article: "Many people do not think about death until it is too late and their family is left to make decisions for them. This article discusses the importance of end-of-life planning and how to prepare for the end of life.",
    link: "./blogentries/estatepreparation",
  },
  {
    id: 5,
    title: "A Nurse's Journey: From Reluctant Student to Dedicated Caregiver",
    author: "Cindy Boushie-Hill LPN",
    date: "2025-08-10",
    category: "Voices In Care",
    NewsSection: "Voices In Care",
    image: "/images/oldschoolnurse.jpg",
    article: "A personal memoir reflecting on the transformation from an unmotivated high school student to a passionate healthcare professional, sharing memorable experiences and lessons learned throughout a nursing career.",
    link: "./blogentries/nursejourneymemoryblogentry",
  },
  {
    id: 6,
    title: "What is an End-of-Life Doula and What Role Do They Have in End of Life Care?",
    author: "Kimberly Dorisio",
    date: "2026-03-06",
    category: "Voices In Care",
    NewsSection: "Voices In Care",
    image: "/images/endoflifedoula.svg",
    article: "As we move through life we plan for many life events—college, marriage, children, retirement—but very few plan for end of life. An End-of-Life Doula can provide emotional, spiritual, and practical support to people and their families who are nearing end of life.",
    link: "./blogentries/endoflifedoulablogentry",
  }
];
