

export const blogData = [
  {
    NewsSection: "Moonshine's Corner",
    image: "./images/moonshine.jpg",
    title: "How I Herded Hearts Instead of Sheep",
    article: "Moonshine introduces himself as a caring, loving nursing companion who tried to be a therapy dog but, while too scared to do so, still inspired elderly patients.",
    date: new Date().toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' }),
    category: "MoonshinesCorner",
    author: "Moonshine",
    id: 1,
    link: "./blogentries/moonshinesblogentry",
  },
  {
    NewsSection: "Senior Policy Beat",
    image: "./images/beach.jpg",
    title: "Medicare Home Health: What Seniors Need to Know",
    article: "Medicare home health services can provide essential support for seniors, including skilled nursing care, physical therapy, and home health aide services. This article exlplains the orgins of Home Health and how it has evolved to meet the needs of seniors today and changed to limit the ablility of nurses to provide personal care to seniors.",
    date: new Date().toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' }),
    category: "SeniorPolicyBeat",
    author: "Karen Underwood RN BSN",
    id: 2,
    link: "./blogentries/seniorpolicybeatblogentry",
  },
  {
    NewsSection: "Voices In Care",
    image: "./images/grandma.jpg",
    title: "The Heart of Hospice Nursing: Compassion, Comfort, and Connection",
    article: "A reflection upon the importance of Hospice nurses from our very own Hospice nurse",
    date: new Date().toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' }),
    category: "rehabsolutions",
    author: "Rehab Solutions Team",
    id: 3,
    link: "./blogentries/voicesincareblogentries",
  },
  {
    NewsSection: "What to do before you die",
    image: "./images/grandma.jpg",
    title: "What to do before you die",
    article: "Many people do not think about death until it is too late and their family is left to make decisions for them. This article discusses the importance of end-of-life planning and how to prepare for the end of life.",
    date: new Date().toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' }),
    category: "Senior Living Desk",
    author: "Karen Underwood RN BSN",
    id:4,
    link: "./blogentries/estatepreparation",
  },
  {
    NewsSection: "Voices In Care",
    image: "./images/Nurse.jpg",
    title: "A Nurse's Journey: From Reluctant Student to Dedicated Caregiver",
    article: "A personal memoir reflecting on the transformation from an unmotivated high school student to a passionate healthcare professional, sharing memorable experiences and lessons learned throughout a nursing career.",
    date: new Date().toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' }),
    category: "Voices In Care",
    author: "Christie Stephan RN ODG",
    id: 5,
    link: "./blogentries/nursejourneymemoryblogentry",
  },
];

